packages:
  - packages/*

autoInstallPeers: false

engineStrict: true

onlyBuiltDependencies:
  - "@bundled-es-modules/glob"
  - style-dictionary

saveExact: true

savePrefix: ""

strictPeerDependencies: false
